[features]
seeds = true
docs = false

[programs.localnet]
auction_manager = "aucwFHspXAnpzCcgCDnepFisGixxxEhW4rkBVizjXcg"


[workspace]
members = [
  "programs/auction-manager",
]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.test.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000

[test.validator]
url = "https://api.mainnet-beta.solana.com"

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # token-metadata

#
# Metaplex Authorization Rules program.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "auth9SigNpDKz4sJJ1DfCTuZrZNSAgh9sFD3rboVmgg"

#
# Metaplex Authorization Rules account.
#
# If this ever changes, make sure to change the
#
# - tests
# - toml below
#
[[test.validator.clone]]
address = "eBJLFYPxJmMGKuFwpDWkzxZeUrad92kZRC5BJLpzyT9"
